### ISSUE TITLE
django 1.8.4 warning compatibility

### ISSUE THREAD

**Issue by samuelcolvin** [niwinz/django-jinja#136]
with Django 1.8.4 and `TEMPLATE_DEBUG` set in `settings.py` you now get:
```
?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django
 1.8 and the TEMPLATES dictionary takes precedence. You must put the values 
of the following settings into your default TEMPLATES dict: TEMPLATE_DEBUG.
```
But if you try to set `debug` in `options` you get 

```
  File "~/env/local/lib/python2.7/site-packages/django_jinja/backend.py", line 133, in __init__
    self.env = environment_cls(**options)
TypeError: __init__() got an unexpected keyword argument 'debug'
```

**Comment by samuelcolvin** [comment]
`django-jinja==1.4.1`

**Comment by niwinz** [comment]
This is because TEMPLATE_DEBUG is django only settings. You can only set it for django templates.

**Comment by samuelcolvin** [comment]
removing TEMPLATE_DEBUG means tests fail as `context` is `None` for the response from test client requests, so django-jinja is effected by the value of `TEMPLATE_DEBUG`

**Comment by niwinz** [comment]
And this is clearly a bug ;)

**Comment by arunsingh** [comment]
You can fix this bug in this manner.

Set debug in OPTIONS dictionary of your templates settings.py file
DEBUG = True

TEMPLATES = [
    {
        ........
        ........
        'OPTIONS': {
            'debug': DEBUG,
       ........

        },
    },
]

Then remove this line from your settings to stop the warnings

TEMPLATE_DEBUG = DEBUG

**Comment by niwinz** [comment]
django-jinja at this moment has support for a bunch of different versions of django that they have very different kind of peculiarities. And the code really grows and stats to be very ugly.

For the next version of django jinja I will be drop support for django < 1.8 surelly because the code stats to be very hard to maintain. I close this issue bacuase this will be fixed surelly for the next version.
