### ISSUE TITLE
Instrumented rendering removed in 2e1aefd4fa61272881c8c91e3c4164cc6b2cd1ca

### ISSUE THREAD

**Issue by ghost** [niwinz/django-jinja#149]
Hi @niwinz, I was wondering why the hook to `setup_test_environment` was removed in 2e1aefd4fa61272881c8c91e3c4164cc6b2cd1ca, wouldn't that mean that it's currently not working on 1.7? Or would this be covered by 7b605259c1803dfe715cd721656d8e82d418daee on both 1.7 and 1.8?

**Comment by jezdez** [comment]
Woops, written from the wrong account, that was me.

**Comment by niwinz** [comment]
The template instrumentation is already covered by this code: https://github.com/niwinz/django-jinja/blob/2e1aefd4fa61272881c8c91e3c4164cc6b2cd1ca/django_jinja/base.py#L75 so I think that monky patching is just duplicated and not necesary. All test passes related to instrumentation. But If I'm wrong, let me know.

Later, the current master will be the last version that supports django <= 1.7  (I will release a 1.5 probably sooner). And the next version 2.0.0 removes all support for django <= 1.7. This approach is taken  because the code was grow unnecesary with the corresponding  complexity of support django <= 1.6, django 1.7 and django >= 1.8 (pre apps, apps and pluggable templates)

**Comment by jezdez** [comment]
@niwinz Ah, thank you! That plan makes total sense, the dual implementation must be painful to maintain. Many thanks for your work in that regard.

**Comment by jezdez** [comment]
Ah a related question, we're using the last released version of django-jinja in an attempt to upgrade to 1.8 and found an issue in which an app was passing in a Django Context object to the template render method.

Since the old 1.7 code has a native Jinja2 Template class that collapses the Context object into a dict (via `dict_from_context`) I was able to fix that by assigning that custom template class to the Jinja2 environment of the 1.8 backend (https://github.com/mozilla/kuma/commit/ecb253b0d39f667e7963c75010813ca4f61499ae). Should that collapsing also be happening in django-jinja's 1.8 backend?

**Comment by niwinz** [comment]
I'm not sure if I'm understand your question.  The django-jinja 1.8 backend works a little bit different to the <= 1.7 related code. But as I can observe in the code, the collapsing is not happening on the 1.8 backend and your fix should work in the same way.

However, it maybe should be fixed directly in django-jinja and avoid do any additional fix on the user code base.

**Comment by niwinz** [comment]
2.0.0 is released already with fixed instrumentation.
