### ISSUE TITLE
Template engine is recognized as 'backend' instead of Jinja2

### ISSUE THREAD

**Issue by glogiotatidis** [niwinz/django-jinja#151]
```python
>>> from django.template import engines
>>> engines.all()
[<django_jinja.backend.Jinja2 object at 0x7f4d27a60410>, <django.template.backends.django.DjangoTemplates object at 0x7f4d27a654d0>]
>>> engines.all()[0].name
'backend'
>>> 
```

**Comment by douglas** [comment]
Also, it seems to break django-debug-toolbar:

https://github.com/django-debug-toolbar/django-debug-toolbar/issues/790

What is the best way to fix it ? In django-jinja or in django-debug-toolbar ?

Thanks =)

**Comment by niwinz** [comment]
About the first one, you should pass "NAME": "jinja2" if you want an other name. The django-jinja backend does the same thing that the jinja2 native backend of django.

And

I don't know that problem do you have with django debug toolbar and django-jinja. I'm using them both in few projects and everything works as expected (with exception to "templates" tab that shows nothing because django debug tool bar only works with django template engine.

**Comment by niwinz** [comment]
I have used ddt 1.3, but it seems that 1.4 introduces some changes that breaks compatibility. This seems ddj toolbar issue because 1.3 works perfectly with django-jinja

**Comment by niwinz** [comment]
I have fixed the compatibility with ddt 1.4 in #157

**Comment by niwinz** [comment]
Now 2.1.0 is released and it should work properly with django-debug-toolbar.

**Comment by IlyaSemenov** [comment]
> The django-jinja backend does the same thing that the jinja2 native backend of django.

@niwinz no, it doesn't. The native backend `django.template.backends.jinja2.Jinja2` is put into `ENGINES['jinja2']` (as it takes the containing module name for the key).
