### ISSUE TITLE
Translating terms 

### ISSUE THREAD

**Issue by tomhamiltonstubber** [niwinz/django-jinja#210]
I created #209 after finding a bug when trying to translate 'Hello World' in the following:

`{{ jinja_macro(_('Hello World'), arg_1) }}`

I still can't get this translated, any ideas?

**Comment by niwinz** [comment]
Hmm, Sincirelly, i don't know. Take care that django documentation says explicitly that django's `makemessages` command does not support jinja2. In case of django-jinja, it comes with an adaptation that makes many jinja2 idioms parseable, but NOT ALL syntax is supported.

If you have a better and testable improvement, please the PR is very welcome.

**Comment by tomhamiltonstubber** [comment]
Okay, I'm due to do this this week so I'll see how I get on, or if I need to use a workaround.

**Comment by jappeace** [comment]
A crappy way of working around this is doing:

            

Above your statement. 

The issue is that the regex in here https://github.com/niwinz/django-jinja/blob/master/django_jinja/management/commands/makemessages.py#L64 can't detect within a statement.
I don't know why they don't just remove the {{ and }} parts in that regex.
