### ISSUE TITLE
How access to Jinja2 ENVIRONMENT?

### ISSUE THREAD

**Issue by gandriyko** [niwinz/django-jinja#217]
I want use django-compressor with django-jinja.
http://django-compressor.readthedocs.io/en/latest/jinja2/?highlight=COMPRESS_JINJA2_GET_ENVIRONMENT#offline-compression
It wants access to Jinja2 ENVIRONMENT  via COMPRESS_JINJA2_GET_ENVIRONMENT.
In what way I could do it?

**Comment by niwinz** [comment]
```python
>>> from django_jinja.backend import Jinja2
>>> Jinja2.get_default()
<django_jinja.backend.Jinja2 object at 0x7f9c0e9848d0>
>>> Jinja2.get_default().env
<jinja2.environment.Environment object at 0x7f9c089c2d68>
```

**Comment by jamiecurle** [comment]
Hey,

For anyone else that lands here looking how to connect django-jinja to django-compressor, here's a copy paste.  

I did beat around the bush for a few minutes figuring out how to marry everything up because compressor docs only reference how to wire in JInja.  

In the end it was brutally simple and I felt like a fish who figured out what water was for the first time.


```python

from django_jinja.builtins import DEFAULT_EXTENSIONS as DJANGO_JINJA_DEFAULT_EXTENSIONS
TEMPLATES = [
    {
        "BACKEND": "django_jinja.backend.Jinja2",
         # blah...
        "OPTIONS": {
            # the below line does the deed. is what you're after.
            "extensions": DJANGO_JINJA_DEFAULT_EXTENSIONS + [
                # your other extentions here...
                 "compressor.contrib.jinja2ext.CompressorExtension".  # <<< this is how compressor is passed into the environment
                 # or here.... 
             ],
            # etc etc
         
    }
```

Cheers,

Jamie.
