### ISSUE TITLE
Python 2.7: 'module' object has no attribute 'lru_cache'

### ISSUE THREAD

**Issue by emesik** [niwinz/django-jinja#244]
Hi,

Version 2.5.0 crashes on Python 2.7 even though it's described as py2-compatible.

```
  File "/home/emes/.local/lib/python2.7/site-packages/django_jinja/backend.py", line 114, in <module>
    class Jinja2(BaseEngine):
  File "/home/emes/.local/lib/python2.7/site-packages/django_jinja/backend.py", line 118, in Jinja2
    @functools.lru_cache()
AttributeError: 'module' object has no attribute 'lru_cache'
```

Apparently, `functools.lru_cache` doesn't exist in py2.

**Comment by wizpig64** [comment]
Although release 2.5.0's docs state otherwise, py27 support was indeed removed. PR #248 fixes the docs and invalidates this ticket, but I'm sorry it doesn't fix your problem.

As I'm sure you've heard, Python 2.7 is no longer supported by the python foundation, so my advice to you is to upgrade your project to django 1.11 LTS (assuming you're not already on the last python-2.7 supported django release), and then to python 3.6. Then 2.5.0 should work, and you can proceed to upgrade your project to django 2.2 LTS.

**Comment by auvipy** [comment]
2.6 has no python 2
